// const textField = document.createElement('textarea');
//   textField.className = 'text';
//   document.body.appendChild(textField);
//   const keyboard = document.createElement('div');
//   keyboard.className = 'keyboard';
//   const keyboardButton = document.createElement('div');
//   keyboardButton.className = 'keyboard-buttons';
//   const sectionChoiceLang = document.createElement('section');
//   sectionChoiceLang.className = 'slider-checkbox';
//   const checkboxChoiceLang = document.createElement('input');
//   checkboxChoiceLang.type = 'checkbox';
//   checkboxChoiceLang.className = 'checkbox';
//   const labelForCheckbox = document.createElement('label');
//   labelForCheckbox.className = 'label';
//   labelForCheckbox.htmlFor = 'checkbox';
//   sectionChoiceLang.appendChild(checkboxChoiceLang);
//   sectionChoiceLang.appendChild(labelForCheckbox);
//   keyboard.appendChild(sectionChoiceLang);
//   let lang = 'rus';